#!/bin/bash

SCRIPT="$(readlink --canonicalize-existing "$0")"
SCRIPTPATH="$(dirname "$SCRIPT")"

PATH="$PATH:$SCRIPTPATH" $(dirname $0)/compiler/tool/cl-tool.js $*
#echo 111

#echo "cl finish" $?
#exit $?